name: 'Test Go'
description: 'Tests a golang project'
inputs:
  go-version:
    description: 'Version of golang to use'
    required: false
    default: '~1.18'
  working-directory:
    description: 'Directory to run the command from'
    required: false
    default: 'test'
  pre-command:
    description: 'Command to run before running tests. Can be used to configure private repositories, etc'
    required: false
    default: ''
  command:
    description: 'Command to run'
    required: false
    default: "go test -v"
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go With Caching
      uses: magnetikonline/action-golang-cache@v1
      with:
        go-version: ${{ inputs.go-version }}
    - name: Test
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        ${{ inputs.pre-command }}
        ${{ inputs.command }}